# Generated by Django 6.0.1 on 2026-03-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='runs',
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, upload_to='players/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
