# Generated by Django 6.0.1 on 2026-03-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_player_runs_player_country_player_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Strike_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
    ]
