# Generated by Django 6.0.1 on 2026-03-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_player_strike_rate_player_matches_player_runs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='odi_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='t20_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='test_matches',
            field=models.IntegerField(default=0),
        ),
    ]
