# Generated by Django 6.0.1 on 2026-03-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_player_odi_matches_player_t20_matches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='odi_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='t20_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='test_runs',
            field=models.IntegerField(default=0),
        ),
    ]
