# Generated by Django 6.0.1 on 2026-05-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Strike_rate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='odi_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='odi_runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='t20_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='t20_runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wickets',
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('TEST', 'Test'), ('ODI', 'ODI'), ('T20', 'T20'), ('IPL', 'IPL')], max_length=10)),
                ('matches', models.IntegerField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('high_score', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='team.player')),
            ],
            options={
                'unique_together': {('player', 'format')},
            },
        ),
    ]
