# Generated by Django 6.0.1 on 2026-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_remove_player_strike_rate_remove_player_matches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='bowling_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='economy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='five_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='four_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
    ]
